 ////////////////////////////////////////////////////
//                                                 //
//  TIE Corps Dress Uniform                        //
//  Service Award Ribbons                          //
//                                                 //
//  Settings in this file are not affected by TTT  //
//                                                 //
////////////////////////////////////////////////////


#include "ribbons_o.inc";


// RIBBONS


#declare T_r_moi =
texture
{
  pigment { image_map { gif ".\ribbons\moi.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moi_bc =
texture
{
  pigment { image_map { gif ".\ribbons\moi-bc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moi_gc =
texture
{
  pigment { image_map { gif ".\ribbons\moi-gc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moi_pc =
texture
{
  pigment { image_map { gif ".\ribbons\moi-pc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moi_ec =
texture
{
  pigment { image_map { gif ".\ribbons\moi-ec.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moi_dc =
texture
{
  pigment { image_map { gif ".\ribbons\moi-dc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_mos_cr =
texture
{
  pigment { image_map { gif ".\ribbons\mos-cr.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_mos_br =
texture
{
  pigment { image_map { gif ".\ribbons\mos-br.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_mos_sr =
texture
{
  pigment { image_map { gif ".\ribbons\mos-sr.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_mos_gr =
texture
{
  pigment { image_map { gif ".\ribbons\mos-gr.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_mos_pr =
texture
{
  pigment { image_map { gif ".\ribbons\mos-pr.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_mot_bh =
texture
{
  pigment { image_map { gif ".\ribbons\mot-bh.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_mot_gh =
texture
{
  pigment { image_map { gif ".\ribbons\mot-gh.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_mot_rh =
texture
{
  pigment { image_map { gif ".\ribbons\mot-rh.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_is_bw =
texture
{
  pigment { image_map { gif ".\ribbons\is-bw.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_is_sw =
texture
{
  pigment { image_map { gif ".\ribbons\is-sw.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_is_gw =
texture
{
  pigment { image_map { gif ".\ribbons\is-gw.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_is_pw =
texture
{
  pigment { image_map { gif ".\ribbons\is-pw.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_is_br =
texture
{
  pigment { image_map { gif ".\ribbons\is-br.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_is_sr =
texture
{
  pigment { image_map { gif ".\ribbons\is-sr.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_is_gr =
texture
{
  pigment { image_map { gif ".\ribbons\is-gr.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_is_pr =
texture
{
  pigment { image_map { gif ".\ribbons\is-pr.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_loc =
texture
{
  pigment { image_map { gif ".\ribbons\loc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_loc_cs =
texture
{
  pigment { image_map { gif ".\ribbons\loc-cs.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_loc_is =
texture
{
  pigment { image_map { gif ".\ribbons\loc-is.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_loc_ts =
texture
{
  pigment { image_map { gif ".\ribbons\loc-ts.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_loc_rs =
texture
{
  pigment { image_map { gif ".\ribbons\loc-rs.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_loc_ps =
texture
{
  pigment { image_map { gif ".\ribbons\loc-ps.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_los =
texture
{
  pigment { image_map { gif ".\ribbons\los.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_los_cs =
texture
{
  pigment { image_map { gif ".\ribbons\los-cs.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_los_is =
texture
{
  pigment { image_map { gif ".\ribbons\los-is.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_los_ts =
texture
{
  pigment { image_map { gif ".\ribbons\los-ts.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_los_rs =
texture
{
  pigment { image_map { gif ".\ribbons\los-rs.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_los_ps =
texture
{
  pigment { image_map { gif ".\ribbons\los-ps.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_dfc =
texture
{
  pigment { image_map { gif ".\ribbons\dfc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_dfc_bw =
texture
{
  pigment { image_map { gif ".\ribbons\dfc-bw.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_dfc_sw =
texture
{
  pigment { image_map { gif ".\ribbons\dfc-sw.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_dfc_gw =
texture
{
  pigment { image_map { gif ".\ribbons\dfc-gw.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moc_boc =
texture
{
  pigment { image_map { gif ".\ribbons\moc-boc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moc_soc =
texture
{
  pigment { image_map { gif ".\ribbons\moc-soc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moc_goc =
texture
{
  pigment { image_map { gif ".\ribbons\moc-goc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moc_poc =
texture
{
  pigment { image_map { gif ".\ribbons\moc-poc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_moc_doc =
texture
{
  pigment { image_map { gif ".\ribbons\moc-doc.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_cos =
texture
{
  pigment { image_map { gif ".\ribbons\cos.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_coe =
texture
{
  pigment { image_map { gif ".\ribbons\coe.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_col =
texture
{
  pigment { image_map { gif ".\ribbons\col.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_cob =
texture
{
  pigment { image_map { gif ".\ribbons\cob.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_1e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-1e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_2e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-2e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_3e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-3e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_4e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-4e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_5e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-5e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_6e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-6e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_7e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-7e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_8e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-8e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_9e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-9e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_10e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-10e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_11e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-11e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_12e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-12e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_13e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-13e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_14e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-14e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_15e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-15e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_16e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-16e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_17e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-17e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_18e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-18e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_19e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-19e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_20e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-20e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_21e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-21e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_22e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-22e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_23e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-23e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_24e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-24e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_25e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-25e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_26e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-26e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_27e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-27e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_28e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-28e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_29e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-29e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_30e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-30e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_31e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-31e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_32e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-32e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_33e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-33e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_34e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-34e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_35e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-35e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_36e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-36e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_37e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-37e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_38e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-38e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

#declare T_r_ov_39e =
texture
{
  pigment { image_map { gif ".\ribbons\ov-39e.gif" } }
  finish  { fin_T_uni }
}
texture { T_unilayer scale 2}

